src/commands/workflow/run.ts
src/lib/api-v1.ts
src/lib/helpers/flag.ts
test/commands/workflow/run.test.ts

Allows a user to run a workflow stored on Knock from the CLI; doesn't include functionality to run a local workflow.
[KNO-3544](https://linear.app/knock/issue/KNO-3544/[cli]-add-workflow-run-command-for-test-running-a-workflow-from-cli)

feat(kno-3544): add workflow run command

---

.github/workflows/on-release-created.yml

I think probably use the latest LTS version instead, which is what we have in the `on-pr-open` action.

chore: update node version in actions

---

src/commands/workflow/run.ts
src/lib/api-v1.ts
src/lib/helpers/flag.ts
src/lib/helpers/json.ts
test/commands/workflow/run.test.ts
test/lib/marshal/workflow/generator.test.ts

The recipient list will start receiving a string containing multiple JSON strings separated by commas. These JSON strings must contain an `id` and can have an optional `collection`, so users can use objects as the recipients/actor.
The same for the actor, this will now receive a JSON string with the required data.
Backend changes: https://github.com/knocklabs/control/pull/2218
[KNO-3908](https://linear.app/knock/issue/KNO-3908/[cli]-rehearse-workflows-using-objects)

feat(KNO-3908): Allow rehearsing workflows using recipients/actors as maps

---

src/lib/marshal/workflow/helpers.ts
src/lib/marshal/workflow/types.ts

Display batch window extension limit on batch step summary
[KNO-3983](https://linear.app/knock/issue/KNO-3983/[cli]-add-batch-extension-limit-to-summary)

feat(kno-3983): add batch window extension limit to summary

---

src/commands/workflow/get.ts
src/lib/marshal/workflow/helpers.ts
src/lib/marshal/workflow/types.ts
src/lib/marshal/workflow/writer.ts
test/lib/marshal/workflow/writer.test.ts

Based on the live discussion last week, we are renaming "if-else" step to "branch" step.
This PR only contains diffs from searching and replacing of `if-else`s or `if_else`s with `branch`s.
[KNO-4102](https://linear.app/knock/issue/KNO-4102/[control]-rename-if-else-step-to-branch-step-everywhere)

chore: rename "if else" step to "branch" step

---

src/commands/layout/pull.ts
src/lib/marshal/email-layout/helpers.ts
src/lib/marshal/email-layout/index.ts
src/lib/marshal/email-layout/reader.ts
src/lib/marshal/email-layout/types.ts
src/lib/marshal/email-layout/writer.ts
src/lib/marshal/shared/helpers.ts
src/lib/marshal/workflow/generator.ts
src/lib/marshal/workflow/helpers.ts
src/lib/marshal/workflow/reader.ts
src/lib/marshal/workflow/writer.ts
src/lib/run-context/loader.ts
src/lib/run-context/types.ts
test/commands/layout/pull.test.ts
test/lib/marshal/layout/reader.test.ts
test/lib/marshal/layout/writer.test.ts
test/lib/marshal/workflow/reader.test.ts

Adds a `layout pull` command for pulling a given email layout into a directory. It also allows to pull all email layouts from a given environment using the `--all` flag along with the `--layout-dir`.
It allows the following flags:
* --environment
* --all
* --layout-dir 
* --hide-uncommitted-changes
* --force
This PR also abstract some logic we use for reading external field contents. Before we used this logic when pulling `workflows`, but now we use the same logic for pulling `layouts`. 
[KNO-4367](https://linear.app/knock/issue/KNO-4367/[cli]-add-pull-email-layout-command)
https://www.loom.com/share/d0035467d1cf48a999536b466d5dd1df

feat(KNO-4367): Add pull email layout command

---

package.json

Add missing layout topic, so the layout command description appears when doing `knock --help`
[KNO-4439](https://linear.app/knock/issue/KNO-4439/[control]-bump-cli-to-015-and-update-topics)

feat(KNO-4439): Add layout topics in package.json

---

src/commands/commit/list.ts
src/lib/api-v1.ts
src/lib/marshal/commit/helpers.ts
src/lib/marshal/commit/index.ts
src/lib/marshal/commit/types.ts
test/commands/commit/list.test.ts
test/lib/api-v1.test.ts
test/support/factory.ts

Adds support for using `knock commit list` command, which lists all commits for a given environment.
Allowed flags:
--promoted (or --no-promoted): Shows all promoted/unpromoted commits for a given environment.
--environment
--json
--limit
--after
--before
[KNO-4537](https://linear.app/knock/issue/KNO-4537/[cli]-add-knock-commit-list-command-in-cli)

feat(KNO-4537): Add "knock commit list" command in cli

---

src/commands/commit/get.ts
src/lib/api-v1.ts
test/commands/commit/get.test.ts
test/lib/api-v1.test.ts

Adds a `knock commit get` command for retrieving one single commit based on an ID.
[KNO-4622](https://linear.app/knock/issue/KNO-4622/[cli]-add-knock-commits-get-command)

feat(KNO-4622) Add "knock commit get" command

---

src/isomorphic.ts
src/lib/marshal/email-layout/helpers.ts
src/lib/marshal/email-layout/index.ts
src/lib/marshal/email-layout/processor.isomorphic.ts
src/lib/marshal/email-layout/reader.ts
src/lib/marshal/email-layout/writer.ts
src/lib/marshal/index.isomorphic.ts
test/lib/marshal/layout/processor.test.ts
test/lib/marshal/layout/writer.test.ts

Similar to #257 where we exported `buildWorkflowDirBundle`, this PR now exports `buildEmailLayoutDirBundle` so we can re-use this helper function in calculating diffs between versions. 
The nature of the changes and the reason for them are exactly the same (except for email layouts than workflows), as well as there is no new functional code in this PR. Refer to the PR description in #257 for more details. 
[KNO-4763](https://linear.app/knock/issue/KNO-4763/[cli]-export-buildemaillayoutdirbundle-helper)

chore: export buildEmailLayoutDirBundle helper

---

src/commands/translation/push.ts
src/lib/marshal/translation/helpers.ts

When pushing translations, skip the `system` translations. If pulled, the system file will be present, but we don't want to push it because in MAPI, it'll always return an error causing the push to fail.
[KNO-5652](https://linear.app/knock/issue/KNO-5652/skip-system-namespace-when-pushing-translations-in-the-cli)

feat: skip system translation files when pushing

---

package.json

Should address the issue reported by a customer, where the newly released v0.1.11 is missing a bin executable: https://knocklabs.slack.com/archives/C01RLET7A6B/p1714425404345129
#290 was included in this release, which upgraded Oclif to the most recent major version 3. And one of the required changes/migration step was to [update bin scripts](https://github.com/oclif/core/blob/main/guides/V3_MIGRATION.md#bin-scripts-for-esmcjs-interoperability) in /bin. What wasn't explicitly called out in the migration guide, but it now appears to be also required is to update the bin path in package.json.
Also, there was an issue in a homebrew release github action from the v0.1.11 release: https://github.com/knocklabs/homebrew-tap/actions/runs/8853400621/job/24314418434. Unclear whether this is a …

fix: point to the right run file for bin

---

src/commands/translation/push.ts
src/lib/marshal/translation/reader.ts
test/lib/marshal/email-layout/reader.test.ts
test/lib/marshal/translation/reader.test.ts

Following up to #320, this PR excludes a system translation file when reading from the disk. The push --all command validates each item before pushing them up one by one, so currently it will fail at the validation step with a system translation file. Excluding from reading should take care of it for both the validate and push operations. 
[KNO-5652](https://linear.app/knock/issue/KNO-5652/skip-system-namespace-when-pushing-translations-in-the-cli)

chore: exclude system translation file when reading from disk

---

package.json

Fixes the issue reported here, where the v0.1.13 release has no commands to run: https://github.com/knocklabs/knock-cli/issues/333
`swc` which we use to build a prod release had a change in behavior in its recent updates ([reference](https://github.com/swc-project/swc/issues/3028)), where it started including a source directory in the output directory. This interfered Oclif from discovering commands because it expects `/commands` directory to be available at the top level. 
```
// Oclif expects this:
dist/
commands/
whoami.js
..
// swc was building like this:
dist/
src/
commands/
whoami.js
...
```
`swc` then added a `--strip-leading-paths` flag to revert this behavior ([here](https://github.com/swc-project/cli/issues/281)), and this PR now passes in this flag when building /dist. …

fix: pass in --strip-leading-paths to swc when building

---

src/commands/translation/get.ts
src/commands/translation/pull.ts
src/lib/api-v1.ts
src/lib/marshal/translation/helpers.ts
src/lib/marshal/translation/processor.isomorphic.ts
src/lib/marshal/translation/writer.ts
test/commands/translation/get.test.ts
test/commands/translation/pull.test.ts

Adds the option to get and pull translation content in the po format. Updates the writer to write to .json or .po files depending on the format flag.
[KNO-5913](https://linear.app/knock/issue/KNO-5913/export-translations-as-po-from-cli)

feat: add option to get and pull translation content in po format

---

src/lib/marshal/email-layout/processor.isomorphic.ts
src/lib/marshal/index.isomorphic.ts
src/lib/marshal/message-type/index.ts
src/lib/marshal/message-type/processor.isomorphic.ts
src/lib/marshal/message-type/types.ts
src/lib/marshal/partial/processor.isomorphic.ts
src/lib/marshal/partial/types.ts
src/lib/marshal/shared/helpers.isomorphic.ts
src/lib/marshal/workflow/processor.isomorphic.ts
test/lib/marshal/email-layout/processor.test.ts
test/lib/marshal/message-type/processor.test.ts
test/lib/marshal/partial/processor.test.ts
test/lib/marshal/workflow/processor.test.ts

A prerequisite for https://github.com/knocklabs/control/pull/3600, to be able to show commit diffs for message types.
[KNO-6509](https://linear.app/knock/issue/KNO-6509/[cli]-add-buildmessagetypedirbundle-helper)

feat: add buildMessageTypeDirBundle helper

---

src/commands/message-type/get.ts
src/commands/message-type/list.ts
src/lib/api-v1.ts
src/lib/marshal/message-type/types.ts
test/commands/commit/get.test.ts
test/commands/layout/get.test.ts
test/commands/layout/push.test.ts
test/commands/layout/validate.test.ts
test/commands/message-type/get.test.ts
test/commands/message-type/list.test.ts
test/commands/partial/get.test.ts
test/commands/partial/push.test.ts
test/commands/partial/validate.test.ts
test/commands/ping.test.ts
test/commands/translation/get.test.ts
test/commands/translation/push.test.ts
test/commands/translation/validate.test.ts
test/commands/whoami.test.ts
test/commands/workflow/activate.test.ts
test/commands/workflow/get.test.ts
test/commands/workflow/push.test.ts
test/commands/workflow/run.test.ts
test/commands/workflow/validate.test.ts
test/support/factory.ts

This PR adds the get and the list commands for message types. (i.e. `knock message-type list` and `knock message-type get ...`). Depends on https://github.com/knocklabs/control/pull/4300.
Will do the pull command in a separate PR.
https://linear.app/knock/issue/KNO-5966/[cli]-knock-message-type-list-and-get-commands

feat: add message-type list and get commands

---

src/commands/message-type/push.ts
src/commands/message-type/validate.ts
src/lib/api-v1.ts
src/lib/marshal/message-type/types.ts
test/commands/message-type/push.test.ts
test/commands/message-type/validate.test.ts

Adds the knock message-type `validate` and `push` commands. The implementation is mostly the same as other resource command modules.
[KNO-7502](https://linear.app/knock/issue/KNO-7502/[cli]-knock-validatepush-message-type-commands)

feat: add message-type push and validate commands

---

src/commands/pull.ts
test/commands/pull.test.ts

This PR adds a new command to the Knock CLI: `knock pull`
This command pulls all email layouts, partials, translations, and workflows into a given directory. Resources will be stored in dedicated subdirectories. For example, if the command `knock pull --knock-dir my-directory` is used, workflows will be stored in `/my-directory/workflows`.
This new command works by delegating to the existing resource-specific `pull` commands. [The oclif docs generally discourage this approach](https://oclif.io/docs/running_programmatically), but this feels like the fastest way to add a “pull all” command without significantly refactoring all existing pull commands. The unit tests I added will make sure we don’t break the `knock pull` command in the future if we ever modify one of the resource-specific …

feat(KNO-8790): add command to pull all resources

---

src/lib/marshal/email-layout/processor.isomorphic.ts
src/lib/marshal/email-layout/types.ts
src/lib/marshal/guide/types.ts
src/lib/marshal/message-type/types.ts
src/lib/marshal/partial/types.ts
src/lib/marshal/shared/helpers.isomorphic.ts
src/lib/marshal/workflow/types.ts
test/commands/guide/push.test.ts
test/commands/layout/push.test.ts
test/commands/message-type/push.test.ts
test/commands/partial/push.test.ts
test/commands/push.test.ts
test/commands/workflow/push.test.ts
test/lib/marshal/email-layout/processor.test.ts
test/lib/marshal/guide/processor.test.ts
test/lib/marshal/message-type/processor.test.ts
test/lib/marshal/partial/processor.test.ts
test/lib/marshal/workflow/processor.test.ts

This PR updates the CLI so that when we store the serialized representations of resources, we remove the `sha` and `updated_at` properties from `__readonly`.
[KNO-8764](https://linear.app/knock/issue/KNO-8764/cli-remove-readonly-properties-from-serialized-resources)

feat(KNO-8764): remove sha and updated_at properties from serialized resources

---

src/lib/marshal/email-layout/reader.ts
src/lib/marshal/guide/reader.ts
src/lib/marshal/message-type/reader.ts
src/lib/marshal/partial/reader.ts
src/lib/marshal/workflow/reader.ts
test/lib/marshal/email-layout/reader.test.ts
test/lib/marshal/guide/reader.test.ts
test/lib/marshal/message-type/reader.test.ts
test/lib/marshal/partial/reader.test.ts
test/lib/marshal/workflow/reader.test.ts

This PR removes the `withReadonlyField` option from the various functions used to read resource directories. It appears we never set `withReadonlyField` to `true` anywhere within the codebase. 
[KNO-8961](https://linear.app/knock/issue/KNO-8961/cli-remove-withreadonlyfield-option-from-directory-read-functions)

chore(KNO-8961): remove withReadonlyField option

---

src/commands/commit/list.ts
src/lib/api-v1.ts
test/commands/commit/list.test.ts

This PR introduces two new filtering parameters, `resource_type` and `resource_id`, to the `knock commit list` command.
**What:**
- Added `--resource-type` (enum: `email_layout`, `guide`, `message_type`, `partial`, `translation`, `workflow`) and `--resource-id` (string) flags to `src/commands/commit/list.ts`.
- Implemented validation to ensure both flags are used together; an error is thrown if only one is provided.
- Updated `src/lib/api-v1.ts` to pass these new parameters (`resource_type`, `resource_id`) to the `listCommits` API method.
**Why:**
- To enable users to filter the list of commits by a specific resource type and identifier, enhancing the command's utility for targeted commit inspection.
**How:**
- Flags were defined with appropriate types and descriptions in the command …

feat: add resource type and id filtering to commits

---

src/commands/partial/get.ts
src/commands/partial/list.ts
src/commands/partial/pull.ts
src/commands/partial/push.ts
src/commands/partial/validate.ts
src/lib/api-v1.ts
test/commands/partial/get.test.ts
test/commands/partial/list.test.ts
test/commands/partial/pull.test.ts
test/commands/partial/push.test.ts
test/commands/partial/validate.test.ts

This PR adds an optional `--branch` flag to `knock partial` commands. This flag will remain hidden until we release branching to GA.
[KNO-9917](https://linear.app/knock/issue/KNO-9917/cli-add-branch-flag-to-partial-commands)

chore(KNO-9917): add branch flag to partial commands

---

src/commands/message-type/get.ts
src/commands/message-type/list.ts
src/commands/message-type/pull.ts
src/commands/message-type/push.ts
src/commands/message-type/validate.ts
src/lib/api-v1.ts
test/commands/message-type/get.test.ts
test/commands/message-type/list.test.ts
test/commands/message-type/pull.test.ts
test/commands/message-type/push.test.ts
test/commands/message-type/validate.test.ts

This PR adds an optional `--branch` flag to `knock message-type` commands. This flag will remain hidden until we release branching to GA.
[KNO-9916](https://linear.app/knock/issue/KNO-9916/cli-add-branch-flag-to-message-type-commands)

chore(KNO-9916): add branch flag to message type commands

---

src/commands/workflow/activate.ts
src/commands/workflow/generate-types.ts
src/commands/workflow/get.ts
src/commands/workflow/list.ts
src/commands/workflow/pull.ts
src/commands/workflow/push.ts
src/commands/workflow/run.ts
src/commands/workflow/validate.ts
src/lib/api-v1.ts
src/lib/urls.ts
test/commands/workflow/activate.test.ts
test/commands/workflow/generate-types.test.ts
test/commands/workflow/get.test.ts
test/commands/workflow/list.test.ts
test/commands/workflow/pull.test.ts
test/commands/workflow/push.test.ts
test/commands/workflow/run.test.ts
test/commands/workflow/validate.test.ts

This PR adds an optional `--branch` flag to `knock workflow` commands. This flag will remain hidden until we release branching to GA.
[KNO-9919](https://linear.app/knock/issue/KNO-9919/cli-add-branch-flag-to-workflow-commands)

chore(KNO-9919): add branch flag to workflow commands

---

src/commands/commit/index.ts
src/lib/api-v1.ts
test/commands/commit/index.test.ts

This PR adds an optional `--branch` flag to the `knock commit` command. This flag will remain hidden until we release branching to GA.
[KNO-9938](https://linear.app/knock/issue/KNO-9938/cli-add-branch-flag-to-commit-command)

chore(KNO-9938): add branch flag to commit command
